# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Courses: /courses
  Archives: /archives
  Presentations: /presentations
  About: /about


# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: true
  Custom: true

widget_custom:
    title: 微信公众号
    content: <img alt="微信公众号：程序员精进" title="微信公众号：程序员精进" src="/images/programmer_viriya_qr_code_scan_500.png">

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

#MobShare
sharesdk: true
shareSDKappkey: 2652bf8c6afe9

# copyright license
post_copyright: true

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname: cheng-xu-yuan-jing-jin


# ===========================================
# Version
# ===========================================
version: 1.1
